// Indian Food Catalog Data
const foodItems = [
    {
      name: "Aloo Gobi (Potato Cauliflower Curry)",
      region: "North Indian",
      spiceLevel: 5,
      sweetLevel: 0,
      hasNuts: false,
      hasDairy: false,
      hasGluten: false,
      isVeg: true,
      isVegan: true,
      isNonveg: false,
      type: "Lunch/Dinner",
      image: "./images/aloo_gobi.jpg",
      description: "A classic vegetarian dish made with potatoes (aloo), cauliflower (gobi), and Indian spices. It's dry and has a beautiful yellow-orange hue from turmeric.",
      recipe: "Sauté cumin seeds, add ginger-garlic paste, turmeric, coriander, and cumin powder. Add potatoes and cauliflower, cover and cook until tender. Garnish with fresh cilantro."
    },
    {
      name: "Chicken Biryani",
      region: "North Indian/South Indian",
      spiceLevel: 7,
      sweetLevel: 0,
      hasNuts: true,
      hasDairy: true,
      hasGluten: false,
      isVeg: false,
      isVegan: false,
      isNonveg: true,
      type: "Lunch/Dinner",
      image: "./images/biryani.jpg",
      description: "A fragrant rice dish cooked with aromatic spices, herbs, and either meat, fish, eggs, or vegetables. The dish is known for its distinct aroma and layers of flavor.",
      recipe: "Marinate meat in yogurt and spices. Partially cook basmati rice with whole spices. Layer meat and rice in a pot, top with fried onions, mint, and saffron milk. Seal with dough and cook on low heat until done."
    },
    {
      name: "Bisibelebath (Lentil Soup)",
      region: "South Indian",
      spiceLevel: 7,
      sweetLevel: 1,
      hasNuts: true,
      hasDairy: false,
      hasGluten: false,
      isVeg: true,
      isVegan: true,
      isNonveg: false,
      type: "Lunch/Dinner",
      image: "./images/bisibelebath.jpg",
      description: "A spicy, rice-based dish with origins in Karnataka. Made with rice, lentils, vegetables, and a special spice powder, it's a complete meal in itself.",
      recipe: "Cook rice and dal together. Prepare tempering with mustard seeds, curry leaves, and asafoetida. Add vegetables, bisibelebath spice powder, tamarind juice, and jaggery. Mix with rice and dal, garnish with cashews and coriander."
    },
    {
      name: "Chepala Pulusu (Fish Curry)",
      region: "South Indian",
      spiceLevel: 8,
      sweetLevel: 3,
      hasNuts: false,
      hasDairy: false,
      hasGluten: false,
      isVeg: false,
      isVegan: false,
      isNonveg: true,
      type: "Lunch/Dinner",
      image: "./images/chepala_pulusu.jpg",
      description: "A tangy fish curry from Andhra Pradesh, known for its spiciness and tamarind-based gravy. It's typically made with local freshwater fish.",
      recipe: "Marinate fish pieces with turmeric and salt. Sauté mustard seeds, fenugreek, cumin, and curry leaves. Add onions, tomatoes, tamarind juice, and spices. Simmer, then add fish and cook until done."
    },
    {
      name: "Dokhla (rice cake)",
      region: "North Indian",
      spiceLevel: 0,
      sweetLevel: 5,
      hasNuts: true,
      hasDairy: false,
      hasGluten: false,
      isVeg: true,
      isVegan: true,
      isNonveg: false,
      type: "Snack",
      image: "./images/dokhla.jpg",
      description: "A savory snack from Gujarat made with fermented rice and chickpea batter. Steamed and then tempered with mustard seeds and curry leaves, it has a unique texture and taste.",
      recipe: "Ferment rice and chickpea flour batter. Add ginger, green chili paste, and turmeric. Steam until set. Temper with mustard seeds, curry leaves, and green chilies. Garnish with coriander and grated coconut."
    },
    {
      name: "Dosa (Savory Pancake)",
      region: "South Indian",
      spiceLevel: 4,
      sweetLevel: 1,
      hasNuts: false,
      hasDairy: false,
      hasGluten: false,
      isVeg: true,
      isVegan: true,
      isNonveg: false,
      type: "Breakfast",
      image: "./images/dosa.jpg",
      description: "A thin, crispy pancake made from fermented rice and lentil batter. Popular across South India, it's typically served with chutney and sambar.",
      recipe: "Soak rice and urad dal separately, then grind into a smooth batter. Ferment overnight. Spread thinly on a hot griddle, add oil around edges, cook until golden and crisp."
    },
    {
      name: "Vada (Donut-shaped Fritter)",
      region: "North Indian",
      spiceLevel: 5,
      sweetLevel: 0,
      hasNuts: false,
      hasDairy: false,
      hasGluten: true,
      isVeg: true,
      isVegan: true,
      isNonveg: false,
      type: "Breakfast",
      image: "./images/gaare.jpg",
      description: "A savory, crispy South Indian fritter or doughnut-shaped snack made from urad dal (black gram) batter. Often served with coconut chutney and sambar.",
      recipe: "Soak urad dal overnight, grind to a smooth batter. Add spices and chopped onions. Shape into doughnuts and deep fry until golden brown. Serve with chutney."
    },
    {
      name: "Gajarela (Carrot Pudding)",
      region: "North Indian",
      spiceLevel: 0,
      sweetLevel: 9,
      hasNuts: true,
      hasDairy: true,
      hasGluten: false,
      isVeg: true,
      isVegan: false,
      isNonveg: false,
      type: "Dessert",
      image: "./images/gajarela.jpg",
      description: "A sweet dessert made from grated carrots, milk, sugar, and cardamom, slow-cooked to perfection. Also known as Gajar ka Halwa.",
      recipe: "Sauté grated carrots in ghee. Add milk and cook until absorbed. Add sugar, cardamom powder, and continue cooking until thick. Garnish with nuts and serve warm."
    },
    {
      name: "Gulab Jamun (Sweet Dumplings)",
      region: "North Indian/South Indian",
      spiceLevel: 0,
      sweetLevel: 10,
      hasNuts: true,
      hasDairy: true,
      hasGluten: true,
      isVeg: true,
      isVegan: false,
      isNonveg: false,
      type: "Dessert",
      image: "./images/gulab_jamun.jpg",
      description: "Soft, spongy milk-solid balls soaked in rose-flavored sugar syrup. One of India's most popular desserts, served at festivals and celebrations.",
      recipe: "Mix milk powder, flour, and baking soda. Add ghee and milk to form a soft dough. Shape into small balls and deep fry on low heat until golden. Soak in sugar syrup flavored with cardamom and rose water."
    },
    {
      name: "Idli (Steamed Rice Cake)",
      region: "South Indian",
      spiceLevel: 2,
      sweetLevel: 0,
      hasNuts: false,
      hasDairy: false,
      hasGluten: false,
      isVeg: true,
      isVegan: true,
      isNonveg: false,
      type: "Breakfast",
      image: "./images/idli.jpg",
      description: "Soft, steamed cakes made from fermented rice and lentil batter. A staple breakfast item in South India, known for being light and healthy.",
      recipe: "Soak rice and urad dal separately, then grind into a smooth batter. Ferment overnight. Pour into idli molds and steam for 10-12 minutes until cooked through."
    },
    {
      name: "Jalebi (Spiral-shaped Sweet)",
      region: "North Indian",
      spiceLevel: 0,
      sweetLevel: 10,
      hasNuts: false,
      hasDairy: false,
      hasGluten: true,
      isVeg: true,
      isVegan: true,
      isNonveg: false,
      type: "Dessert",
      image: "./images/jalebi.jpg",
      description: "Crispy, pretzel-shaped deep-fried sweets soaked in sugar syrup. Bright orange in color, they're a popular street food and festival treat.",
      recipe: "Make a fermented batter with flour, yogurt, and a pinch of turmeric. Pipe spiral shapes into hot oil and fry until crisp. Soak in saffron-infused sugar syrup."
    },
    {
      name: "Jeera Rice (Cumin Rice)",
      region: "North Indian",
      spiceLevel: 2,
      sweetLevel: 0,
      hasNuts: false,
      hasDairy: false,
      hasGluten: false,
      isVeg: true,
      isVegan: true,
      isNonveg: false,
      type: "Lunch/Dinner",
      image: "./images/jeera_rice.jpg",
      description: "Basmati rice cooked with cumin seeds, offering a simple yet aromatic side dish that pairs well with curries and dals.",
      recipe: "Rinse and soak basmati rice. Sauté cumin seeds in ghee until they crackle. Add rice, water, salt and cook until fluffy. Garnish with coriander leaves."
    },
    {
      name: "Kodi Kura (Spicy Chicken Curry)",
      region: "South Indian",
      spiceLevel: 9,
      sweetLevel: 1,
      hasNuts: false,
      hasDairy: false,
      hasGluten: false,
      isVeg: false,
      isVegan: false,
      isNonveg: true,
      type: "Lunch/Dinner",
      image: "./images/kodi_kura.jpg",
      description: "A fiery Andhra-style chicken curry flavored with red chilies and traditional spices. Known for its intense heat and rich flavor.",
      recipe: "Marinate chicken with yogurt and spices. Sauté onions, ginger-garlic paste, and Andhra spice mix. Add tomatoes, chicken, and cook until tender. Finish with fresh curry leaves."
    },
    {
      name: "Laddu",
      region: "North Indian/South Indian",
      spiceLevel: 0,
      sweetLevel: 8,
      hasNuts: true,
      hasDairy: true,
      hasGluten: false,
      isVeg: true,
      isVegan: false,
      isNonveg: false,
      type: "Dessert",
      image: "./images/laddu.jpg",
      description: "Sweet, ball-shaped treats made from various ingredients like gram flour, semolina, or coconut. A traditional offering at temples and celebrations.",
      recipe: "Roast gram flour in ghee until aromatic. Add sugar syrup and cardamom powder. Mix well and shape into round balls while still warm. Garnish with pistachios."
    },
    {
      name: "Motichoor Laddu",
      region: "North Indian",
      spiceLevel: 0,
      sweetLevel: 9,
      hasNuts: true,
      hasDairy: true,
      hasGluten: true,
      isVeg: true,
      isVegan: false,
      isNonveg: false,
      type: "Dessert",
      image: "./images/motichoor_laddu.jpg",
      description: "A special type of laddu made from tiny gram flour balls (boondi) soaked in sugar syrup. Known for its melt-in-mouth texture and orange hue.",
      recipe: "Make tiny droplets of gram flour batter in hot oil. Drain and soak in saffron-flavored sugar syrup. Mix with cardamom powder and chopped nuts. Shape into balls while still moist."
    },
    {
      name: "Pakodi (Fritters)",
      region: "North Indian",
      spiceLevel: 6,
      sweetLevel: 0,
      hasNuts: false,
      hasDairy: false,
      hasGluten: true,
      isVeg: true,
      isVegan: true,
      isNonveg: false,
      type: "Snack",
      image: "./images/pakodi.jpg",
      description: "Crispy fritters made from gram flour batter and various vegetables or herbs. A popular tea-time snack, especially during monsoon season.",
      recipe: "Mix gram flour with spices, water, and chopped onions, spinach, or other vegetables. Drop spoonfuls into hot oil and fry until golden and crisp. Serve with chutney."
    },
    {
      name: "Palak Paneer (Spinach with Cottage Cheese)",
      region: "North Indian",
      spiceLevel: 5,
      sweetLevel: 1,
      hasNuts: false,
      hasDairy: true,
      hasGluten: false,
      isVeg: true,
      isVegan: false,
      isNonveg: false,
      type: "Lunch/Dinner",
      image: "./images/palak_paneer.jpg",
      description: "A creamy curry made with spinach (palak) and cottage cheese (paneer). The vibrant green dish is packed with nutrients and flavor.",
      recipe: "Blanch spinach and blend into a puree. Sauté onions, garlic, ginger, and tomatoes with spices. Add spinach puree and simmer. Fold in paneer cubes and garnish with cream."
    },
    {
      name: "Paratha (Stuffed Flatbread)",
      region: "North Indian",
      spiceLevel: 4,
      sweetLevel: 1,
      hasNuts: false,
      hasDairy: true,
      hasGluten: true,
      isVeg: true,
      isVegan: false,
      isNonveg: false,
      type: "Breakfast/Lunch/Dinner",
      image: "./images/paratha.jpg",
      description: "Layered, flaky flatbreads that can be plain or stuffed with various fillings like potatoes, cauliflower, or paneer. A staple in North Indian cuisine.",
      recipe: "Make dough with whole wheat flour, water, and salt. Roll out, apply ghee, fold, and roll again for layers. Cook on a hot griddle, applying ghee until golden and crisp on both sides."
    },
    {
      name: "Pav Bhaji (Sweet Bread with Spicy Vegetable Mash)",
      region: "North Indian",
      spiceLevel: 6,
      sweetLevel: 3,
      hasNuts: false,
      hasDairy: true,
      hasGluten: true,
      isVeg: true,
      isVegan: false,
      isNonveg: false,
      type: "Lunch/Dinner",
      image: "./images/pav_bhaji.jpg",
      description: "A popular street food consisting of spicy mashed vegetables (bhaji) served with soft bread rolls (pav). Originated in Mumbai and now loved nationwide.",
      recipe: "Boil and mash mixed vegetables. Sauté onions, garlic, ginger, and tomatoes with pav bhaji masala. Add mashed vegetables and cook. Serve with butter-toasted pav and chopped onions."
    },
    {
      name: "Payasam (Rice Pudding)",
      region: "South Indian",
      spiceLevel: 0,
      sweetLevel: 8,
      hasNuts: true,
      hasDairy: true,
      hasGluten: false,
      isVeg: true,
      isVegan: false,
      isNonveg: false,
      type: "Dessert",
      image: "./images/payasam.jpg",
      description: "A traditional pudding made with milk, rice or vermicelli, sugar, and flavored with cardamom and nuts. An essential part of South Indian festivals.",
      recipe: "Sauté vermicelli or rice in ghee until golden. Add milk and cook until soft. Add sugar, cardamom powder, and simmer until thick. Garnish with cashews, raisins, and saffron."
    },
    {
      name: "Poori (Deep-fried Bread)",
      region: "North Indian/South Indian",
      spiceLevel: 3,
      sweetLevel: 0,
      hasNuts: false,
      hasDairy: false,
      hasGluten: true,
      isVeg: true,
      isVegan: true,
      isNonveg: false,
      type: "Breakfast",
      image: "./images/poori.jpg",
      description: "Deep-fried, puffy bread made from whole wheat flour. Typically served with potato curry, chole, or halwa as part of a traditional breakfast.",
      recipe: "Knead whole wheat flour, salt, and oil into a firm dough. Roll into small circles. Deep fry in hot oil until they puff up and turn golden brown."
    },
    {
      name: "Roti (Flatbread)",
      region: "North Indian",
      spiceLevel: 2,
      sweetLevel: 0,
      hasNuts: false,
      hasDairy: false,
      hasGluten: true,
      isVeg: true,
      isVegan: true,
      isNonveg: false,
      type: "Lunch/Dinner",
      image: "./images/roti.jpg",
      description: "A simple, unleavened flatbread made from whole wheat flour, cooked on a flat griddle. A staple accompaniment to meals across North India.",
      recipe: "Mix whole wheat flour with water to make a soft dough. Divide into small balls, roll into thin circles. Cook on a hot tawa (griddle) until light brown spots appear on both sides."
    },
    {
      name: "Samosa",
      region: "North Indian",
      spiceLevel: 7,
      sweetLevel: 2,
      hasNuts: false,
      hasDairy: false,
      hasGluten: true,
      isVeg: true,
      isVegan: true,
      isNonveg: false,
      type: "Snack",
      image: "./images/samosa.jpg",
      description: "Triangular pastries filled with spiced potatoes, peas, and sometimes meat. One of India's most recognized snacks, popular both as street food and at home.",
      recipe: "Make dough with flour, salt, and oil. For filling, sauté cumin seeds, potatoes, peas, and spices. Form triangular pockets with dough, fill, seal, and deep fry until golden."
    },
    {
      name: "Tandoori Chicken",
      region: "North Indian",
      spiceLevel: 7,
      sweetLevel: 1,
      hasNuts: false,
      hasDairy: true,
      hasGluten: false,
      isVeg: false,
      isVegan: false,
      isNonveg: true,
      type: "Lunch/Dinner",
      image: "./images/tandoori_chicken.jpg",
      description: "Chicken marinated in yogurt and spices, then roasted in a tandoor (clay oven). Known for its distinctive red color and smoky flavor.",
      recipe: "Marinate chicken in yogurt, lemon juice, ginger-garlic paste, and tandoori masala. Let sit for several hours. Traditionally cooked in a tandoor, but can be baked in an oven until charred and cooked through."
    },
    {
      name: "Vangibath (Eggplant Rice)",
      region: "South Indian",
      spiceLevel: 6,
      sweetLevel: 1,
      hasNuts: true,
      hasDairy: false,
      hasGluten: false,
      isVeg: true,
      isVegan: true,
      isNonveg: false,
      type: "Lunch/Dinner",
      image: "./images/vangibath.jpg",
      description: "A flavorful rice dish made with eggplant (brinjal) and a special spice powder. Popular in Karnataka, it's known for its distinct aroma and taste.",
      recipe: "Sauté eggplant cubes with onions and vangibath spice powder (coriander, chana dal, urad dal, red chilies, and fenugreek). Mix with cooked rice. Temper with mustard seeds, curry leaves, and garnish with roasted peanuts."
    }
  ];